# dags

dag <- 'dag {
  "Solar input" -> "SST"
  "Solar input" -> "Primary productivity"
  "Solar input" -> "Season"
  "SST" -> "Primary productivity"
  "SST" -> "Macroalgae cover"
  "Primary productivity" -> "Macroalgae cover"
  "Primary productivity" -> "Reef fish biomass"
  "Reef area" -> "Primary productivity"
  "Reef area" -> "Reef fish biomass"
  "Coast length" -> "Reef area"
  "Geomorphic type" -> "Primary productivity"
  "Geomorphic type" -> "Reef isolation"
  "Reef isolation" -> "Shark fishing pressure"
  "Reef isolation" -> "Reef fish fishing pressure"
  "Reef isolation" -> "Reef shark abundance"
  "Reef isolation" -> "Reef fish biomass"
  "Season" -> "Reef shark abundance"
  "Macroalgae cover" -> "Reef fish biomass"
  "Macroalgae cover" -> "Hard coral"
  "Depth" -> "Macroalgae cover"
  "Depth" -> "Wave exposure"
  "Depth" -> "Reef type"
  "Reef type" -> "Macroalgae cover"
  "Reef type" -> "Wave exposure"
  "Reef type" -> "Rugosity"
  "Reef type" -> "Hard coral"
  "Wave exposure" -> "Rugosity"
  "Rugosity" -> "Reef fish biomass"
  "Rugosity" -> "Reef shark abundance"
  "Hard coral" -> "Reef fish biomass"
  "Hard coral" -> "Reef shark abundance"
  "Hard coral" -> "Rugosity"
  "Pollution" -> "Primary productivity"
  "Pollution" -> "Macroalgae cover"
  "Pollution" -> "Hard coral"
  "Reef fish biomass" -> "Reef shark abundance"
  "Reef fish fishing pressure" -> "Reef fish biomass"
  "Population size" -> "Pollution"
  "Population size" -> "Human gravity"
  "Human gravity" -> "Pollution"
  "Human gravity" -> "Reef fish fishing pressure"
  "Human gravity" -> "Shark fishing pressure"
  "Human gravity" -> "MPA"
  "Human gravity" -> "MPA compliance"
  "HDI" -> "Voice"
  "HDI" -> "Pollution"
  "HDI" -> "Shark fishing restrictions"
  "HDI" -> "MPA"
  "HDI" -> "MPA compliance"
  "HDI" -> "MPA size"
  "HDI" -> "Reef fish fishing pressure"
  "HDI" -> "Shark fishing pressure"
  "HDI" -> "Human gravity"
  "Government effectiveness" -> "MPA"
  "Government effectiveness" -> "MPA compliance"
  "Government effectiveness" -> "Reef fish fishing pressure"
  "Government effectiveness" -> "Shark fishing pressure"
  "Government effectiveness" -> "Voice"
  "Government effectiveness" -> "Shark fishing restrictions"
  "Government effectiveness" -> "HDI"
  "Government effectiveness" -> "Shark sanctuary"
  "Voice" -> "MPA"
  "Voice" -> "MPA compliance"
  "Voice" -> "Shark fishing restrictions"
  "MPA" -> "Shark fishing pressure"
  "MPA" -> "Reef fish fishing pressure"
  "MPA" -> "Shark fishing restrictions"
  "MPA" -> "MPA age"
  "MPA" -> "MPA compliance"
  "MPA" -> "MPA size"
  "MPA size" -> "Reef fish fishing pressure"
  "MPA size" -> "Shark fishing pressure"
  "MPA compliance" -> "Reef fish fishing pressure"
  "MPA compliance" -> "Shark fishing pressure"
  "MPA age" -> "Reef fish biomass"
  "Shark sanctuary" -> "Shark fishing pressure"
  "Shark sanctuary" -> "Shark fishing restrictions"
  "Shark fishing restrictions" -> "Shark fishing pressure"
  "Shark fishing restrictions" -> "Temporal limits"
  "Shark fishing restrictions" -> "Species limits"
  "Shark fishing restrictions" -> "Gear limits"
  "Shark fishing restrictions" -> "Catch limits"
  "Shark fishing restrictions" -> "Effort limits"
  "Shark fishing restrictions" -> "Size limits"
  "Temporal limits" -> "Shark fishing pressure"
  "Species limits" -> "Shark fishing pressure"
  "Gear limits" -> "Shark fishing pressure"
  "Effort limits" -> "Shark fishing pressure"
  "Size limits" -> "Shark fishing pressure"
  "Catch limits" -> "Shark fishing pressure"
  "Shark fishing pressure" -> "Reef shark abundance"
  "Shark fishing restrictions"[exposure]
  "Reef shark abundance"[outcome]
}
'

dag_revised <- 'dag {
  "Solar input" -> "SST"
  "Solar input" -> "Primary productivity"
  "Solar input" -> "Season"
  "SST" -> "Primary productivity"
  "SST" -> "Macroalgae cover"
  "Primary productivity" -> "Macroalgae cover"
  "Primary productivity" -> "Reef fish biomass"
  "Reef area" -> "Primary productivity"
  "Reef area" -> "Reef fish biomass"
  "Coast length" -> "Reef area"
  "Coast length" -> "Population size"
  "Geomorphic type" -> "Primary productivity"
  "Geomorphic type" -> "Reef isolation"
  "Reef isolation" -> "Shark fishing pressure"
  "Reef isolation" -> "Reef fish fishing pressure"
  "Reef isolation" -> "Reef shark abundance"
  "Reef isolation" -> "Reef fish biomass"
  "Season" -> "Reef shark abundance"
  "Macroalgae cover" -> "Reef fish biomass"
  "Macroalgae cover" -> "Hard coral"
  "Depth" -> "Macroalgae cover"
  "Depth" -> "Wave exposure"
  "Depth" -> "Reef type"
  "Reef type" -> "Macroalgae cover"
  "Reef type" -> "Wave exposure"
  "Reef type" -> "Rugosity"
  "Reef type" -> "Hard coral"
  "Wave exposure" -> "Rugosity"
  "Rugosity" -> "Reef fish biomass"
  "Rugosity" -> "Reef shark abundance"
  "Hard coral" -> "Reef fish biomass"
  "Hard coral" -> "Reef shark abundance"
  "Hard coral" -> "Rugosity"
  "Pollution" -> "Primary productivity"
  "Pollution" -> "Macroalgae cover"
  "Pollution" -> "Hard coral"
  "Reef fish biomass" -> "Reef shark abundance"
  "Reef fish fishing pressure" -> "Reef fish biomass"
  "Population size" -> "Pollution"
  "Population size" -> "Human gravity"
  "Population size" -> "Shark sanctuary"
  "Human gravity" -> "Pollution"
  "Human gravity" -> "Reef fish fishing pressure"
  "Human gravity" -> "Shark fishing pressure"
  "Human gravity" -> "MPA"
  "Human gravity" -> "MPA compliance"
  "HDI" -> "Voice"
  "HDI" -> "Pollution"
  "HDI" -> "Shark fishing restrictions"
  "HDI" -> "MPA"
  "HDI" -> "MPA compliance"
  "HDI" -> "MPA size"
  "HDI" -> "Reef fish fishing pressure"
  "HDI" -> "Shark fishing pressure"
  "HDI" -> "Human gravity"
  "Government effectiveness" -> "MPA"
  "Government effectiveness" -> "MPA compliance"
  "Government effectiveness" -> "Reef fish fishing pressure"
  "Government effectiveness" -> "Shark fishing pressure"
  "Government effectiveness" -> "Voice"
  "Government effectiveness" -> "Shark fishing restrictions"
  "Government effectiveness" -> "HDI"
  "Government effectiveness" -> "Shark sanctuary"
  "Voice" -> "MPA"
  "Voice" -> "MPA compliance"
  "Voice" -> "Shark fishing restrictions"
  "MPA" -> "Shark fishing pressure"
  "MPA" -> "Reef fish fishing pressure"
  "MPA" -> "Shark fishing restrictions"
  "MPA" -> "MPA age"
  "MPA" -> "MPA compliance"
  "MPA" -> "MPA size"
  "MPA size" -> "Reef fish fishing pressure"
  "MPA size" -> "Shark fishing pressure"
  "MPA compliance" -> "Reef fish fishing pressure"
  "MPA compliance" -> "Shark fishing pressure"
  "MPA age" -> "Reef fish biomass"
  "MPA age" -> "MPA compliance"
  "Shark sanctuary" -> "Shark fishing pressure"
  "Shark sanctuary" -> "Shark fishing restrictions"
  "Shark fishing restrictions" -> "Shark fishing pressure"
  "Shark fishing restrictions" -> "Temporal limits"
  "Shark fishing restrictions" -> "Species limits"
  "Shark fishing restrictions" -> "Gear limits"
  "Shark fishing restrictions" -> "Catch limits"
  "Shark fishing restrictions" -> "Effort limits"
  "Shark fishing restrictions" -> "Size limits"
  "Temporal limits" -> "Shark fishing pressure"
  "Species limits" -> "Shark fishing pressure"
  "Gear limits" -> "Shark fishing pressure"
  "Effort limits" -> "Shark fishing pressure"
  "Size limits" -> "Shark fishing pressure"
  "Catch limits" -> "Shark fishing pressure"
  "Shark fishing pressure" -> "Reef shark abundance"
  "Species limits" -> "Gear limits"
  "Species limits" -> "Effort limits"
  "Species limits" -> "Size limits"
  "Size limits" -> "Effort limits"
  "Temporal limits" -> "Catch limits"
  "Shark fishing restrictions"[exposure]
  "Reef shark abundance"[outcome]
}
'